version: '3'

services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: serve -s build -l 3000
    container_name: frontend
    restart: unless-stopped
    networks:
      - realworld-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - realworld-docker-network
    

  api:
    build: ./api
    command: npm run start
    container_name: api
    restart: unless-stopped
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - realworld-docker-network

  auth:
    build: ./auth
    command: npm run start
    container_name: auth
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - realworld-docker-network

  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    container_name: api_db
    networks:
      - realworld-docker-network

  auth_db:
    image: mongo:latest
    volumes:
      - mongodb_auth:/data/db
    container_name: auth_db
    networks:
      - realworld-docker-network

volumes:
  mongodb_api:
  mongodb_auth:
    
networks:
  realworld-docker-network:
    driver: bridge